# Site Info
title: "Site Title"
tagline: "A blog on the internet!"
description: "A blog on the internet. Opinions and views are my own."
url: "" # the base hostname & protocol for your site e.g. "https://HackingPheasant.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"
logo: ""

# Site configurations
feed:
  path: atom.xml
excerpt_separator: <!--more-->
paginate: 10 # amount of posts to show
paginate_path: "/blog/page:num"
permalink: /blog/:year/:month/:day/:title
include: ['_pages']
sass:
  sass_dir: _sass
markdown_ext: "markdown,mkdown,mkdn,mkd,md"



# About/contact
author:
  name: "Your Name"
  avatar: "" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "I am an **amazing** person."
  contact:
    email: "youremail@protonmail.com"
    twitter: username
    github:  username

# Build settings
# remote_theme: HackingPheasant/jekyll-theme-pheasants-nest

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

liquid:
  error_mode: warn
  strict_filters: true
  #strict_variables: true


# Github Pages settings. 
# Cannot be changed. Just setting so we can mimick github pages setup
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
